name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Code coverage-reporter
        uses: tj-actions/coverage-reporter@v5.1
        with:
          coverage-command: "nyc --reporter=text mocha --exclude='fixtures' __tests__/*.js"